### ISSUE TITLE
Dataset path

### ISSUE THREAD

**Issue by yangdaowu** [ly-zhu/Separating-Sounds-from-a-Single-Image#1]
Hello, I'm running your code and building my own dataset, but in music Py has a problem. I don't know how to pass the real data path

![image](https://user-images.githubusercontent.com/64669901/147383717-ad5671d4-5333-423f-a3ed-b628ea67ac91.png)

My data set path is like this：

![image](https://user-images.githubusercontent.com/64669901/147383741-af97a704-c8c0-4e98-be1e-7495ef1d93d9.png)

I want to ask how I should modify it, thank you for your answer.

**Comment by ly-zhu** [comment]
Hi, 

In your case, the path would be: data_path = 'data/'

**Comment by yangdaowu** [comment]
Change according to the method, there is such a problem

![image](https://user-images.githubusercontent.com/64669901/147520497-68d82f9e-4c7b-44db-ac98-3f1b087d30f4.png)

**Comment by ly-zhu** [comment]
The "data_path" here is where you saved your "audio/" and "frames/". Change accordingly (data_path = "xxxx/data/") should work. 
Either way is to set a symbolic link, "ln -s xxxx/data data", and then use data_path = "data/".

"xxxx" is your path of "data/audio" and "data/frames".

**Comment by yangdaowu** [comment]
Good, thank you, I have solved this problem
